"""auto-vote

Revision ID: ded57ff8f4c9
Revises: 189cb4f6f07a
Create Date: 2021-12-01 11:22:36.422190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded57ff8f4c9'
down_revision = '189cb4f6f07a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.alter_column('posts', 'published',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'True'::character varying"))
    op.create_unique_constraint(None, 'users', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('posts', 'published',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'True'::character varying"))
    op.drop_table('votes')
    # ### end Alembic commands ###
